title: AWS RDS AuthorizeDBSecurityGroupIngress Attempt
id: b2f61361-2891-507f-bec2-96a7bf5e0eb9
status: experimental
description: |
    Enables ingress to a DBSecurityGroup using one of two forms of authorization.
    Security implications: Attackers might use AuthorizeDBSecurityGroupIngress to allow unauthorized access to the database by modifying security group rules.
references:
    - https://pages.awscloud.com/rs/112-TZM-766/images/Visibility_detect_respond_AWS_SANS_whitepaper.pdf
    - https://sysdig.com/blog/aws-rds-security-events-sysdig/
    - https://aws.permissions.cloud/iam/rds#rds-AuthorizeDBSecurityGroupIngress
    - https://traildiscover.cloud/#RDS-AuthorizeDBSecurityGroupIngress
author: Zach Mathis (@YamatoSecurity)
date: 2026-07-12
modified: 2026-07-12
tags:
    - attack.defense-evasion
    - attack.t1578 #Modify Cloud Compute Infrastructure
logsource:
    product: aws
    service: cloudtrail
detection:
    selection:
        eventSource: rds.amazonaws.com
        eventName: AuthorizeDBSecurityGroupIngress
    error_code:
        errorCode|exists: true
    error_msg:
        errorMessage|exists: true
    condition: selection and (error_code or error_msg)
falsepositives:
    - Legitimate provisioning or configuration changes by administrators or CI/CD pipelines.
    - Infrastructure-as-code (Terraform, CloudFormation, CDK, Pulumi) applying changes.
level: medium
