title: Add Application
id: 1f333f67-6188-4759-85e2-8b04e5af39d8
status: test
description: 
references:
author: Zach Mathis (@yamatosecurity)
date: 2025-09-29
modified: 2025-09-29
tags:
    - attack.persistence
logsource:
    product: azure
    service: auditlogs
detection:
    selection:
        Operation: 'Add application.'
        Workload: 'AzureActiveDirectory'
    condition: selection
falsepositives:
level: medium