name: Check duplicate UUID in sigma rules
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  checkDuplicateUUID:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/suzaku
          path: suzaku

      - name: Check for duplicate id in yml files
        run: |
          count=$(grep -h '^id:' **/*.yml | sort | uniq -c | sort -nr | grep -v "1 id" | wc -l)
          if [ "$count" -ne 0 ]; then
            echo "Duplicate uuid found in yml files"
            exit 1
          fi