### If you want to execte GitHub Actions on your local machine please use following commnad. (Please install act if needed.)
### act workflow_dispatch -s GITHUB_TOKEN=(your private access token) -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 --artifact-server-path /tmp/act-artifacts

name: Pipeline for sigma rule updates

on:
  ## This workflow is executed once a day.
  ## I added workflow_dispatch so that you can execute this workflow from the GitHub UI.
  workflow_dispatch:

jobs:
  updateSigmaRule:
    runs-on: ubuntu-latest
    steps:
      - name: clone sigma
        uses: actions/checkout@v4
        with:
          repository: SigmaHQ/sigma
          path: sigma-repo
          token: ${{ secrets.GITHUB_TOKEN }} ## This is necessary for executing on a local machine by act(Local GitHub Action Runner). We have to specify the github token explicitly.

      - name: clone suzaku rule repo
        uses: actions/checkout@v4
        with:
          path: suzaku-rules